/**
 * @file MathInterpreterMsg.h
 * Header file for the class that holds interpretation messages
 * 
 * @copyright Copyright 2015 Anthony Tibbs
 * This project is released under the GNU General Public License.
*/

#ifndef __MATH_INTERPRETER_MSG_H__
#define __MATH_INTERPRETER_MSG_H__

#include <iostream>
#include <string>

/**
 * A single message generated by the math interpreter
 */
class MathInterpreterMsg
{
 public:
  typedef enum { INFO, NOTICE, WARNING, ERROR } Category;

 protected:
  Category m_category;
  unsigned long m_code;
  std::string m_filename;
  unsigned long m_line1;
  unsigned long m_line2;
  std::string m_message;

 public:
  MathInterpreterMsg (const MathInterpreterMsg::Category category,
		   const unsigned long msgCode, 
		   const std::string &source_filename, 
		   const unsigned long source_linenumber1,
		   const unsigned long source_linenumber2,
		   const std::string &msg);

  MathInterpreterMsg::Category getCategory (void) const;
  unsigned long getCode (void) const;
  std::string getFilename (void) const;
  unsigned long getStartLineNumber (void) const;
  unsigned long getEndLineNumber (void) const;
  std::string getMessage (void) const;

  friend std::ostream &operator<<(std::ostream &os, const MathInterpreterMsg &mdm);
};

#endif /* __MATH_INTERPRETER_MSG_H__ */
